# Generated by Django 4.1.7 on 2023-07-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_playing_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='playing_user',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
