# Generated by Django 4.1.7 on 2023-07-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_playing_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='playing_user',
            name='channel_name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
