# Generated by Django 4.1.7 on 2023-07-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_playing_user_channel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playing_user',
            name='channel_name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
