# Generated by Django 4.1.7 on 2023-09-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_playing_user_channel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playing_user',
            name='room_name',
            field=models.CharField(max_length=6),
        ),
    ]
